name: Minimal-1
favicon: null
layout_spectrum: 0.25146
typography_spectrum: 0.4875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b19cd9'
  brandStrength: 0.1875
  lightness: 0.4379263923037797
  saturation: 0.7795820508617908
  rhythmicContrast: 0.7952227781061083
purpose: []
